apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    name: sample
spec:
  nodeSelector:
    kubernetes.io/hostname: ford
  volumes:
  - name: sample-persistent-volume
    persistentVolumeClaim:
      claimName: sample-persistent-volume-claim
  containers:
  - name: sample-container
    image: sgs-registry.snucse.org/ws-rzq8iwdacwjd0/base
    command: ['/bin/bash', '-c', 'sleep inf']
    resources:
        limits:
          nvidia.com/gpu: 1
    volumeMounts:
    - name: sample-persistent-volume
      mountPath: /workspace/mount
    env:
    - name: CONDA_PKGS_DIRS
      value: /workspace/mount/conda_pkgs
    - name: CONDA_ENVS_DIRS
      value: /workspace/mount/conda_env
